[FIX] formio: JS form change event ensure submission.metadata.selectData.
Fix for JavaScript (formio.js) error:
TypeError: Cannot read properties of undefined (reading 'selectData')

This is a workaround (formio.js 4.18.2, 4.19.3) to prevent the form change
event from crashing due to missing metadata.selectData,
This affects the change event on a selectboxes component with URL as a Data
Source Type.